[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dataproc-ml"
version = "1.0.0rc1"
authors = [{ name = "Google LLC" }]
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
description = "A python library to ease MLOps for Dataproc customers"
license = "Apache-2.0"
license-files = ["LICENSE*"]
readme = "README.md"
requires-python = ">=3.12"
# Aligned with environment of Cloud Dataproc 2.3 for GCE-ML/serverless image
dependencies = [
    "google-cloud-aiplatform>=1.121.0, <2.0.0",
    "google-cloud-storage>=2.19.0, <3.0.0",
    "google-genai>=1.38.0, <3.0.0",
    "pandas>=2.2.2, <3.0.0",
    "pyarrow>=18.1.0, <20.0.0",
    "tenacity>=8.5.0, <9.0.0",
    "tensorflow>=2.18.0, <2.20.0",
    "torch>=2.6.0, <3.0.0"
]

[project.urls]
Homepage = "https://github.com/GoogleCloudDataproc/dataproc-ml-python"
Documentation = "https://dataproc-ml.readthedocs.io/"
Issues = "https://github.com/GoogleCloudDataproc/dataproc-ml-python/issues"

[project.optional-dependencies]
test = [
    "pytest",
    "torchvision>=0.21.0, <1.0.0",
    "pillow>=11.3.0, <12.0.0",
    # For running tests, a full pyspark installation is needed.
    "pyspark~=4.0.0",
]

dev = [
    "pyink",
    "pylint",
    "build"
]
docs = [
    "sphinx",
    "sphinx_rtd_theme",
]

[tool.pyink]
line-length = 80 # Default is 88

[tool.setuptools.packages.find]
include = ["google*"]
namespaces = true

[tool.pytest.ini_options]
addopts = "--ignore=load/"
